services:
  grafana:
    user: root
    container_name: 'harperdb-grafana-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/harperdb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/harperdb-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.harperdb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: harperdb-datasource

    networks:
      - grafana-harperdb

  harperdb:
    image: harperdb/harperdb
    volumes:
      - ./hdb:/home/harperdb/hdb
    networks:
      - grafana-harperdb
    ports:
      - '49925:9925'
    environment:
      HDB_ADMIN_USERNAME: admin
      HDB_ADMIN_PASSWORD: foobarbaz

networks:
  grafana-harperdb:
